default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: aevam
  password: Password@123
  host: localhost

development:
  <<: *default
  database: rails_development

test:
  <<: *default
  database: rails_test

production:
  primary:
    <<: *default
    database: <%= ENV.fetch("DB_NAME", "rails_production") %>
  cache:
    <<: *default
    database: <%= ENV.fetch("DB_CACHE_NAME", "rails_production_cache") %>
    schema_dump: db/cache_schema.rb
  queue:
    <<: *default
    database: <%= ENV.fetch("DB_QUEUE_NAME", "rails_production_queue") %>
    schema_dump: db/queue_schema.rb
  cable:
    <<: *default
    database: <%= ENV.fetch("DB_CABLE_NAME", "rails_production_cable") %>
    schema_dump: db/cable_schema.rb
